### ISSUE TITLE
Whether there is any possibility of over fitting when rows are all 0

### ISSUE THREAD

**Issue by echosyy** [ssui-liu/learnable-embed-sizes-for-RecSys#1]
Hi, this paper works great for embedding compressed. However, if there are many rows of all 0 in the pruned matrix V, does it mean that all difficult samples are discarded and there is a possibility of fitting?

**Comment by ssui-liu** [comment]
All samples in the dataset will share the same embedding table, so I don't think pruning the embedding table will cause discarding of difficult samples. Besides, the raw features will also been used to make prediction without embedding table. Therefore, it's hard to say they are being dropped.
